import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/pages/Header'
import Cards from '@/Card/Cards'
import Skill from '@/Skills/Skill'
import Contact from '@/Contact/Contact'
import Contacts from '@/pages/Contacts'
import Headers from '@/Header/Headers'
import Introduction from '@/Intoduction/Introduction'
import Project from '@/Proects/Project'
import MainHeader from '@/Header/MainHeader'
import Projects2 from '@/Proects/Projects2'
import About from '@/pages/About'
import Projects3 from '@/Proects/Projects3'
import Button from '@/Proects/Button'
import Projects4 from '@/Proects/Projects4'
import Contact1 from '@/Contact/Contact1'
import ContactPage from '@/Contact/ContactPage'
import Butt from '@/Contact/Butt'
import Headers2 from '@/Header/Headers2'
import Widgets from './Widgets'
import Personal from './Personal'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Victoria's portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
      </Head>
      <div className='text-white bg-[#000] h-screen w-screen snap-y snap-mandatory scroller z-0' id='container'>
        <div className='basic bg-[#000]'>
       
      
      <Headers />
    
      <Header />
      <Headers2/>

      <section className='snap-start bg-[#1116]'>
      <Introduction />
      </section>
      
     
      {/* <section className='snap-center bg-[#000]'>
       <Skill/>
      </section> */}

      </div>
      <div className='bg-[#000]'>

      {/* <section className='snap-center bg-[#111]'>
       <Personal/>
      </section> */}
       <section className='snap-center bg-[#111]'>
       <Project/>
      </section>
      
      

      <section className='snap-center bg-[#000]'>
       <Projects2/>
      </section> 

      <section className='snap-center bg-[#111]'>
       <Projects3/>
      </section>

       <section className='snap-center bg-[#000]'>
       <Projects4/>
      </section> 

      <section className='snap-center bg-[#1111]'>
        <Button/>
      </section>

      <section className='snap-center bg-[#1111]'>
        <Widgets/>
      </section>

      <section className=' bg-[#111]'>
       <About/>
      </section> 

      <section className=' bg-[#000]'>
       <ContactPage/>
      </section>

      </div>
      

      </div>

      
      
    </>
  )
}
